ricokahler/sanity-codegen

- package-lock.json
- package.json
- src/cli.ts
Adds `configFile: false` to the `@babel/register` setup in the CLI for mono repos with a babel config.
> fix: disable config file

- package-lock.json
- package.json
- src/generate-types.test.ts
- src/generate-types.ts
The exported type break if isolated modules is enabled in the tsconfig. This fixes the re-exported types by adding `export type`
> fix: change to export type to comply with isolatedModules

- src/client/create-client.test.ts
- src/client/create-client.ts
Small addition: adds the accept header to the request being made. This isn't really necessary because the Sanity APIs always returns the response as JSON but a proper thing to add regardless.
> chore: add accept header

- README.md
- package-lock.json
- package.json
- rollup.config.js
- scripts/build.js
- src/index.umd.ts
Just tried running this build in next.js and found that the UMD bundles fails (used by SSR) because the regenerator-runtime was not found in the code.
> fix: include regenerator-runtime for UMD bundle

- package-lock.json
- package.json
- src/no-op.ts
- src/schema-creator-shim.ts
I ran into a bug when running codegen. If you import `withDocument` like so
```ts
import { withDocument } from 'part:@sanity/form-builder';
```
it breaks because the no-op package only resolves to one function. This fix greatly improves the no-op by creating this forever recursive object that you can forever invoke without it ever throwing… it's kind of fun.
Paste this into your console for a whirl
```js
const proxy = new Proxy(
function () {
return proxy;
},
{
get: () => proxy,
}
);
proxy.fjeiw().oaf.fewafew.affdj().sfejs.fj.ghr.vhrvreh.hr.e.feiwojio()()()()()() // doesn't throw!
```
> fix: improve no-op with expando proxy

- package-lock.json
- package.json
- src/generate-types.test.ts
- src/generate-types.ts
I included a change back in #10 to do `export type`. During that time I should've also made it do `import type` too.
> fix: `import type` too

- package-lock.json
- package.json
- src/types.ts
There's a typo in the types.
I meant `_createdAt` but instead I had `_createAt`
> fix: _createAt typo

- README.md
- package-lock.json
- package.json
- src/client/create-client.test.ts
- src/client/create-client.ts
This PR adds a method to the sanity client `query` that simply passes the query to your sanity instance. It includes preview-mode logic where draft IDs are preferred in preview mode.
> feat: add query method

- src/generate-types.test.ts
- src/generate-types.ts
First of all, great job with this tool! Makes using Sanity with Typescript much more enjoyable!
I was having issues using this codegen tool as is, because field names and types in my Studio are all `snake_case`.
As Sanity allows underscores in their types and field names, I fixed the code so snake_case fields and types work well. For types, the Type Name won't have the underscores in it, as it is not very "Typescriptish" to have underscores in Type and Interface Names.
For example, `foo_bar` type will be `FooBar` in Typescript. 
Documentation should probably be updated too following this change.
> Correctly handle type names having underscores

- package-lock.json
- package.json
- src/client/create-client.test.ts
- src/client/create-client.ts
This PR adds a simple caching mechanism to the client.
The client is nice a simple but I've learned it can quickly eat quotas when in heavy development 😅. This cache should remove a dimension and speed up builds as well.
---
This has been published to `sanity-codegen@next` if you wanted to try it before it's released
> feat: client cache

- README.md
- package-lock.json
- package.json
- src/augments.d.ts
- src/cli.ts
- src/types.ts
This enables extra babel options to be passed to the CLI prior to running code gen.
My use case for this was working with a monorepo. By default babel doesn't compile anything in `node_modules` including symlinked packages that yarn workspaces creates.
> feat: babel options

- package-lock.json
- package.json
- rollup.config.js
I tried using sanity codegen's client inside sanity studio and… it won't compile!
I think this is because Sanity's using a webpack version that's over 3 years old (v3.8.1). The sanity babel config ignores node_modules by default however it's common practice for the ESM modules (`.esm.js`) to use newer javascript but the object spread operator is apparently too new for webpack 3.
> fix: sanity client build in sanity

- .babelrc
- package-lock.json
- package.json
I think babel or browerslist recently updated something where `targets: { node: true }` no-longer compiles optional chaining down.
This results in a smaller node build but also breaks vercel deploys (because they still use the last LTS, node 12).
Anyway, this fixes that.
> fix: change preset env targets

- package-lock.json
- package.json
- src/cli.ts
This adds the babel plugin `css-modules-transform` so that CSS modules can "run" in node without throwing in the CLI
> fix: resolve css modules imports

- package-lock.json
- package.json
- src/generate-types.test.ts
- src/generate-types.ts
- tsconfig.typecheck.json
The types in my test ended up breaking due to some typescript upgrade. It wasn't caught by the tests because the typecheck command skipped the tests. This ensure typecheck runs it through the tests.
> chore: reconfigure typecheck to work with tests

- README.md
- package-lock.json
- package.json
- src/client/create-client.test.ts
- src/client/create-client.ts
Allows the client to use `apicdn.sanity.io`. Adds a `useCdn` flag
> feat: cdn client

- README.md
- package-lock.json
- package.json
- src/client/create-client.ts
This adds the method `.setPreviewMode()` to the client allowing for preview mode to be set after the object's creation.
This is useful for next.js preview mode.
> feat: mutable preview mode

- package-lock.json
- package.json
- src/client/create-client.ts
Fixes a bug where the token is not sent unless preview mode is active. Now the token will be sent regardless of preview mode.
> fix(client): fix incorrect token condition

- package-lock.json
- package.json
- src/client/create-client.ts
The `v` prefix isn't actually required by the official client so we'll change that here to match
> fix(client): remove `v` prefix for `apiVersion`

- packages/groq-codegen/src/__example-files__/example-file.ts
- packages/groq-codegen/src/__example-files__/example-schema.ts
- packages/groq-codegen/src/generate-groq-types.test.ts
- packages/groq-codegen/src/generate-groq-types.ts
- packages/groq-codegen/src/pluck-groq-from-files.test.ts
There's a small bug where references don't land in the final codegen file (e.g. `query-types.d.ts`).
> fix(groq-codegen): fix bug with references not showing up

- package-lock.json
- package.json
- src/cli.ts
Closes #214 
Uses a similar method as the schema extractor in the Sanity CLI for GraphQL deploys
> fix(cli): use jsdom-global to shim out browser deps

- packages/extractor/src/schema-executor.ts
- packages/extractor/src/schema-extractor.ts
This MR attempts to improve how child process exits are handled.
Problems I encountered and solved by this fix:
- infinite process indicator when child process exited due to unhandled errors. In my case it happened because of broken installation was thrown because of a missing package
- calling `process.exit(0)` caused that the caller process never receive the message sent with `process!.send(...)`, even when sucessful (not sure why this happens). Just setting `process.exitCode` and letting the process to end normally worked well
Notes:
- I added a `loadAndExecute().then(...)` callback to handle the success case. This way:
- both success and error cases are handled as close together (parsing and sending messages)
- the `loadAndExecute` function returns the schema, and the parsing is done …
> fix(v1): safer handling of child process exits
